log:
  formatter: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  stream_handler_level: INFO
  file_handler_level: INFO
#level: WARNING
#stream_handler_level: DEBUG
#file_handler_level: DEBUG
